
name: generate from jinja2 templates

on:
  push:
    branches: [ master ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  install-packages:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-python@v2
      with:
        python-version: 3.x
    - run: |
        pip3 install --user --upgrade j2cli
        j2 --version
